# services:
#   - docker

# If PR, create a review app.
install:
  - echo "⏳ Install phase"
  # - touch $TRAVIS_BUILD_DIR/envs/dev.env
  # - touch $TRAVIS_BUILD_DIR/envs/secrets.env
  # - make run
# script:
#   - echo "🧪 PR En cours"


after_success:
  - echo "🎉 Success!"

  # clever published-config set <variable-name> <variable-value>


jobs:
  include:
    # - stage: test
    #   script:
    #     - echo "🧪 PR En cours"
    #     - make test
    - stage: create-review-app
      env:
        - ORGANIZATION_NAME=Miimosa
        - APP_NAME=itou-celinems
        - REVIEW_APP_NAME=$APP_NAME-$TRAVIS_BRANCH
      if: branch != master
      script:
        - echo "🛸 Build disposable staging"
        - echo $REVIEW_APP_NAME
        - echo $TRAVIS_BRANCH
        - curl https://clever-tools.cellar.services.clever-cloud.com/releases/latest/clever-tools-latest_linux.tar.gz > clever-tools-latest_linux.tar.gz
        - tar -xvf clever-tools-latest_linux.tar.gz
        - ./clever-tools-latest_linux/clever login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
        - ./clever-tools-latest_linux/clever create $REVIEW_APP_NAME -t node --org $ORGANIZATION_NAME --region par --alias $REVIEW_APP_NAME
        - ./clever-tools-latest_linux/clever domain add $REVIEW_APP_NAME.cleverapps.io --alias $REVIEW_APP_NAME
        - ./clever-tools-latest_linux/clever scale --flavor S --alias $REVIEW_APP_NAME
        - ./clever-tools-latest_linux/clever deploy
    # - stage: destroy-review-app
    #   script: echo "EXTERMINATE!"

