# Generated by Django 2.2.10 on 2020-03-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE EXTENSION IF NOT EXISTS unaccent;
                DROP TEXT SEARCH CONFIGURATION IF EXISTS french_unaccent;
                CREATE TEXT SEARCH CONFIGURATION french_unaccent ( COPY = french );
                ALTER TEXT SEARCH CONFIGURATION french_unaccent
                  ALTER MAPPING FOR hword, hword_part, word
                  WITH unaccent, french_stem;
            """,
            reverse_sql="""
                DROP TEXT SEARCH CONFIGURATION french_unaccent;
            """,
        )
    ]
